"""add lesson_minutes and price_eur to booking model

Revision ID: c4cb6b59775b
Revises: f3ae018d2bb8
Create Date: 2026-01-21 14:20:17.504607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cb6b59775b'
down_revision = 'f3ae018d2bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price_eur', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('price_eur')
        batch_op.drop_column('lesson_minutes')

    # ### end Alembic commands ###
